### ISSUE TITLE
What is GCP_BUCKET and GCP_PROJECT in example google_storage?

### ISSUE THREAD

**Issue by sumedhburbure** [raphaelbs/esp32-cam-ai-thinker#11]
I am trying to implement the google_storage example for esp-cam. I have followed the README.md and have successfully generated the device code,access token and refresh token for the said scope on google console. However while setting the menuconfig , I am not aware of the parameters GCP_BUCKET and GCP_PROJECT. I tried to search for BUCKET concept and configured a bucket for my google cloud. Should I give my bucket name for GCP_BUCKET? and what to input for GCP_PROJECT?

**Comment by raphaelbs** [comment]
@sumedhburbure yes.
In [google console](https://console.cloud.google.com) you can list your projects.
`GCP_PROJECT` is your project Id. Should be something like `name-1237`.

For `GCP_BUCKET` you can search for `Storage` in the search bar.
GCP will list all buckets for your selected project.
Select the name of the bucket. Usually is an `prefix.appspot.com`.
