### ISSUE TITLE
Error when loading in M5Cam

### ISSUE THREAD

**Issue by martarho** [raphaelbs/esp32-cam-ai-thinker#15]
I am trying to adapt the google-storage example code in this repo to my M5Cam, but despite trying to force it to recognise the 4Mb RAM, it still crashes with this error:

E (489) spiram: Expected 8192KiB chip but found 4096KiB chip. Bailing out..

Are there any reasons why the code here should not work with my ESP32-based board? Thanks!

**Comment by raphaelbs** [comment]
You can try change `CONFIG_SPIRAM_TYPE` config in your `sdkconfig` as shown [in the docs](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html?highlight=sdkconfig#config-spiram-type).

**Comment by martarho** [comment]
Hey, managed to fix it :) thanks

**Comment by raphaelbs** [comment]
@martaho I would appreciate if you share what was the solution. Thanks
