### ISSUE TITLE
OV7725 camera support

### ISSUE THREAD

**Issue by ashishbindal93** [raphaelbs/esp32-cam-ai-thinker#18]
#feature request

Please share code for OV7725 with ai-thinker esp32 board

<a href="https://ibb.co/82DfMXZ"><img src="https://i.ibb.co/ZK6FdND/IMG-20190823-185247790.jpg" alt="IMG-20190823-185247790" border="0"></a>

**Comment by raphaelbs** [comment]
Hello @ashishbindal93 
The code in this repository was heavily based in `https://github.com/espressif/esp32-camera`.
You can put together this examples with `OV7725` sensor support available there.

Also, I would be grateful with you contribute to this repo by uploading your code once you got it working.

**Comment by ashishbindal93** [comment]
Didn't get that working. I have tried all the codes available but no code works for this setup.

**Comment by ashishbindal93** [comment]
I can provide you pinning for the ov7725 camera module and esp cam board.

**Comment by ashishbindal93** [comment]
Any update over OV7725?
Anyone got that working?
