### ISSUE TITLE
CONFIG_RESET was not declared ?

### ISSUE THREAD

**Issue by otakexplode** [raphaelbs/esp32-cam-ai-thinker#35]
I tried running the main file and this was what i got , im guessing im missing some files but I can't seem to locate which one . Please kindly help thanks

**Comment by raphaelbs** [comment]
Can you share some log?

**Comment by raphaelbs** [comment]
Please try to build it again using PlatformIO. The setup is so much easier.
Feel free to re-open the issue if it still persist.
