### ISSUE TITLE
编译 http_jpg报错fatal error: mdns.h: No such file or directory  #include <mdns.h

### ISSUE THREAD

**Issue by rose387** [raphaelbs/esp32-cam-ai-thinker#37]
请问怎么解决？
recipe for target 'src/scheme_softap.o' failed
make[1]: *** [src/scheme_softap.o] Error 1
recipe for target 'component-wifi_provisioning-build' failed
make: *** [component-wifi_provisioning-build] Error 2

**Comment by raphaelbs** [comment]
Please try to build it again with PlatformIO.
Feel free to re-open the issue in case still does not work.
