### ISSUE TITLE
Refreshing auth token

### ISSUE THREAD

**Issue by tomaszblachowiak** [raphaelbs/esp32-cam-ai-thinker#9]
I'm trying to use your example with google integration. I manage to compile and upload the code to ESP32-CAM. I stuck on:

I (65397) example_google_storage: Refresh auth token...
E (67617) example_google_storage: Parse FAIL!
I (67617) example_google_storage: Status = 400
I (67617) example_google_storage: Checking bucket access []...
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

How to troubleshoot error 400? I followed your guide three times to tripple check if I miss something...
I put all the configuration in Kconfig.projbuild

  menu "Google Cloud Configuration"
    config GCP_CLIENT_ID
      string "5****r.apps.googleusercontent.com"
    config GCP_CLIENT_SECRET
      string "f****g"
    config GCP_REFRESH_TOKEN
      string "1%2F7KxQnAi****o"
    config GCP_DEVICE_CODE
      string "AH-1Ng2-R****6J7S32k6EgQxLL9YF4ubbElnU1-De-K7LQ"
    config GCP_BUCKET
      string "esp32-cam-timelapse.appspot.com"
    config GCP_PROJECT
      string "esp32-cam-timelapse"
  endmenu

**Comment by raphaelbs** [comment]
Hi @tomaszblachowiak 

Have you successfully obtained refresh token via `curl` or `postman`?

Also, you should enable debugging level to get more information about the http request.
Change `sdkconfig` from

> CONFIG_LOG_DEFAULT_LEVEL_INFO=y

to

> CONFIG_LOG_DEFAULT_LEVEL_INFO=
> CONFIG_LOG_DEFAULT_LEVEL_DEBUG=y
